public class controlContactTriggerRecursion {
    public Static list<contact> LstOFContactNeedToUdpdateInAfterTrigger = new list<contact>();
    public static boolean AllowTriggerFlag = true;
    public static boolean AllowcontactTrigger = true;
    public static boolean ControlLeadTriggerRecurtion = true;
    public static boolean AllowAfterTriggerFlag = true;
    public static boolean AllowAfterEmailTriggerFlag = true;
    public static boolean ControlERPContactsTrigger = true;
    public static boolean ControlActivateContact = true;
    public static boolean ControlNonAmbassadorReferralsTrigger = true;
    public static boolean ControlReferralsTrigger = true;
    public static boolean ControlAmbReferralsTrigger = true;
    public static boolean ControlNetExamTrigger = true;
}