@isTest
public class leadUpdateLastClickQueueableTest {
   /*  static testmethod void test1() {
         Lead lead1p = new lead(lastname='Test',company='Tst', Phone='(925)-499-9000', Channel__c = 'Billboard', Custom_Lead_Source__c= 'Billboard : Brilliant');		
         Lead lead2p = new lead(lastname='Test',company='Tst', Phone='(925)-499-9000', Channel__c = 'Billboard', Custom_Lead_Source__c= 'Billboard : Brilliant',
                                Campaign__c='gosolar', Keywords__c = 'solar', Content__c = '1111_content', Technology__c='web' );		
         insert lead1p; 
         insert lead2p; 
         Set<Id> leadIdSet = new Set<Id>(); 
         Set<Id> leadIdSet1 = new Set<Id>(); 
         Set<Id> deleteLeadIdSet = new Set<Id>(); 

         leadIdSet.add(lead2p.id); 
           
         Test.startTest();
         System.enqueueJob(new leadUpdateLastClickQueueable(leadIdSet, leadIdSet1, deleteLeadIdSet));
         Test.stopTest();
     } */
}