public class loadRelatedRecordsQueueable{
 /* public class loadRelatedRecordsQueueable implements Queueable{

   public Set<Id> leadIdSet {get;set;}
    public Set<Id> deleteLeadIdSet {get;set;}
    
    public loadRelatedRecordsQueueable() {
    	this(null, null);
    }
    
    public loadRelatedRecordsQueueable(Set<Id> leadIdSet, Set<Id> deleteLeadIdSet) {
        this.leadIdSet = leadIdSet;
        this.deleteLeadIdSet = deleteLeadIdSet; 
    }
      
    public void execute(QueueableContext ctx) {
           LeadDeDupServiceImpl.loadRelatedRecords(leadIdSet, deleteLeadIdSet);             
    }
       */    
}