public class srvcConsoleUtil {

    public static string Account = 'Account';
    public static string Opportunity = 'Opportunity';
    public static string Cases = 'Case';
    public static string Contact = 'Contact';
   public static string Proposals = 'Proposals';
    public static string ServiceContract = 'ServiceContract';
    public static string FSDispatch = 'FSDispatch';
    public static string SCE = 'ServiceContractEvent';
     public static string ServiceTransfer = 'ServiceTransfer';
}